<?php
// POST /api/submit_application.php
// Submits a new vehicle registration application

require_once 'config.php';

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { respond(['error' => 'Method not allowed'], 405); }

$session = requireAuth(['public', 'officer', 'admin']);
$body    = json_decode(file_get_contents('php://input'), true);

// Validate vehicle fields
$required = ['vehicle_type_id','make','model','year','color','chassis_number','fuel_type','application_type'];
foreach ($required as $field) {
    if (empty($body[$field])) {
        respond(['error' => "Missing field: $field"], 422);
    }
}

$year = (int)$body['year'];
if ($year < 1950 || $year > (int)date('Y') + 1) {
    respond(['error' => 'Invalid vehicle year'], 422);
}

$validFuels = ['Petrol','Diesel','Electric','Hybrid'];
if (!in_array($body['fuel_type'], $validFuels)) {
    respond(['error' => 'Invalid fuel type'], 422);
}

$validTypes = ['new','renewal','transfer'];
if (!in_array($body['application_type'], $validTypes)) {
    respond(['error' => 'Invalid application type'], 422);
}

$db = getDB();

// Check chassis number not already registered (for new applications)
if ($body['application_type'] === 'new') {
    $stmt = $db->prepare("SELECT id FROM vehicles WHERE chassis_number = ?");
    $stmt->execute([strtoupper(trim($body['chassis_number']))]);
    if ($stmt->fetch()) {
        respond(['error' => 'A vehicle with this chassis number already exists'], 409);
    }
}

// Validate vehicle type
$stmt = $db->prepare("SELECT id, registration_fee FROM vehicle_types WHERE id = ?");
$stmt->execute([(int)$body['vehicle_type_id']]);
$vehicleType = $stmt->fetch();
if (!$vehicleType) {
    respond(['error' => 'Invalid vehicle type'], 422);
}

$db->beginTransaction();
try {
    // Insert vehicle
    $stmt = $db->prepare("INSERT INTO vehicles (owner_id, vehicle_type_id, make, model, year, color, chassis_number, engine_number, fuel_type)
                          VALUES (?,?,?,?,?,?,?,?,?)");
    $stmt->execute([
        $session['user_id'],
        (int)$body['vehicle_type_id'],
        trim($body['make']),
        trim($body['model']),
        $year,
        trim($body['color']),
        strtoupper(trim($body['chassis_number'])),
        !empty($body['engine_number']) ? strtoupper(trim($body['engine_number'])) : null,
        $body['fuel_type'],
    ]);
    $vehicleId = $db->lastInsertId();

    // Insert application (reference number generated by trigger)
    $stmt = $db->prepare("INSERT INTO applications (vehicle_id, applicant_id, application_type, status)
                          VALUES (?,?,?,'pending')");
    $stmt->execute([$vehicleId, $session['user_id'], $body['application_type']]);
    $applicationId = $db->lastInsertId();

    // Fetch the generated reference number
    $stmt = $db->prepare("SELECT reference_number FROM applications WHERE id = ?");
    $stmt->execute([$applicationId]);
    $ref = $stmt->fetchColumn();

    // Create pending payment record
    $stmt = $db->prepare("INSERT INTO payments (application_id, amount, currency, status) VALUES (?,?,'BWP','pending')");
    $stmt->execute([$applicationId, $vehicleType['registration_fee']]);

    $db->commit();

    auditLog($session['user_id'], 'APPLICATION_SUBMITTED', 'applications', $applicationId, "Ref: $ref");

    respond([
        'message'          => 'Application submitted successfully.',
        'application_id'   => (int)$applicationId,
        'reference_number' => $ref,
        'fee_amount'       => (float)$vehicleType['registration_fee'],
        'status'           => 'pending',
    ], 201);

} catch (Exception $e) {
    $db->rollBack();
    respond(['error' => 'Failed to submit application. Please try again.'], 500);
}
